import cssText from "data-text:~style.css"
import type { PlasmoCSConfig } from "plasmo"
import kuromoji from "kuromoji"
import { createRoot } from "react-dom/client"
import React, { useEffect, useRef, useState } from "react"
import WordCard from "~components/WordCard"
export const getStyle = () => {
  const style = document.createElement("style")
  style.textContent = cssText
  return style
}

export const config: PlasmoCSConfig = {
  matches: ["*://*.youtube.com/watch*"],
  all_frames: false
}

interface Token {
  surface_form: string
}

interface JMDictEntry {
  kanji?: string[]
  kana?: string[]
  senses?: Array<{
    gloss: string[]
  }>
}

declare global {
  interface Window {
    jmdictData: JMDictEntry[]
    jmdictIndex: Record<string, JMDictEntry>
    jmdictKanaIndex: Record<string, JMDictEntry>
    jmdictLoaded: boolean
    kuromojiTokenizer: any
  }
}

class YouTubeSubtitleManipulator {
  private isEnabled: boolean = false
  private isInitialized: boolean = false
  private lastCaptionText: string = ""
  private updateInterval: NodeJS.Timeout | null = null
  private observer: MutationObserver | null = null
  private wordCardContainer: HTMLDivElement | null = null
  private wordCardRoot: any = null

  private wordCard: {
    word: string
    mouseX: number
    mouseY: number
    isVisible: boolean
    isSticky: boolean
  } = {
    word: "",
    mouseX: 0,
    mouseY: 0,
    isVisible: false,
    isSticky: false
  }

  constructor() {
    this.setupMessageListener()
    this.initializeJapanese()
    this.checkExtensionEnabled()
  }

  private async checkExtensionEnabled(): Promise<void> {
    try {
      const result = await this.getUseAutoGeneratedSubtitles()
      this.isEnabled = result

      if (this.isEnabled) {
        console.log("[YouTube Manipulator] Auto-generated mode enabled, initializing")
        this.init()
      } else {
        console.log("[YouTube Manipulator] Auto-generated mode disabled")
      }
    } catch (error) {
      console.error("[YouTube Manipulator] Error checking state:", error)
      this.isEnabled = false
    }
  }

  private async getUseAutoGeneratedSubtitles(): Promise<boolean> {
    return new Promise((resolve) => {
      if (typeof chrome !== "undefined" && chrome.runtime) {
        chrome.runtime.sendMessage(
          { action: "getUseAutoGeneratedSubtitles" },
          (response) => {
            if (chrome.runtime.lastError) {
              console.log("[YouTube Manipulator] Could not get state, assuming disabled")
              resolve(false)
            } else {
              resolve(response?.useAutoGenerated || false)
            }
          }
        )
      } else {
        resolve(false)
      }
    })
  }

  private async initializeJapanese(): Promise<void> {
    try {
      if (!window.kuromojiTokenizer) {
        const tokenizer = await new Promise<any>((resolve, reject) => {
          kuromoji
            .builder({
              dicPath: chrome.runtime.getURL("node_modules/kuromoji/dict/")
            })
            .build((err, tokenizer) => {
              if (err) {
                reject(err)
                return
              }
              resolve(tokenizer)
            })
        })
        window.kuromojiTokenizer = tokenizer
      }

      if (!window.jmdictLoaded) {
        try {
          const response = await fetch(
            chrome.runtime.getURL(
              "assets/data/japanese/jmdict-simplified-flat-full.json"
            )
          )
          window.jmdictData = await response.json()
          window.jmdictIndex = {}
          window.jmdictKanaIndex = {}

          window.jmdictData.forEach((entry) => {
            if (Array.isArray(entry.kanji)) {
              entry.kanji.forEach((kanji) => {
                window.jmdictIndex[kanji] = entry
              })
            }
            if (Array.isArray(entry.kana)) {
              entry.kana.forEach((kana) => {
                window.jmdictKanaIndex[kana] = entry
              })
            }
          })

          window.jmdictLoaded = true
          console.log("[YouTube Manipulator] JMdict loaded:", window.jmdictData.length, "entries")
        } catch (e) {
          console.error("[YouTube Manipulator] Failed to load JMdict:", e)
          window.jmdictData = []
          window.jmdictIndex = {}
          window.jmdictKanaIndex = {}
          window.jmdictLoaded = true
        }
      }

      this.isInitialized = true
    } catch (error) {
      console.error("[YouTube Manipulator] Failed to initialize Japanese processing:", error)
      this.isInitialized = false
    }
  }

  private init(): void {
    if (!this.isEnabled) {
      console.log("[YouTube Manipulator] Not enabled, skipping initialization")
      return
    }

    if (!window.location.href.includes("youtube.com/watch")) {
      console.log("[YouTube Manipulator] Not on watch page")
      return
    }

    this.createReactWordCard()
    this.startMonitoring()
    this.observeNavigation()

    console.log("[YouTube Manipulator] Initialized")
  }

  private createReactWordCard(): void {
    if (document.getElementById("bundai-youtube-wordcard-root")) {
      document.getElementById("bundai-youtube-wordcard-root")?.remove()
    }

    this.wordCardContainer = document.createElement("div")
    this.wordCardContainer.id = "bundai-youtube-wordcard-root"
    this.wordCardContainer.className = "react-word-card-container"

    document.body.appendChild(this.wordCardContainer)

    this.wordCardRoot = createRoot(this.wordCardContainer)
    this.renderWordCard()
  }

  private renderWordCard(): void {
    if (!this.wordCardRoot || !this.wordCardContainer) return
  
    const captionContainer = document.querySelector(".captions-text")
    const containerRect = captionContainer?.getBoundingClientRect() || null
  
    this.wordCardRoot.render(
      <WordCard
        word={this.wordCard.word}
        mouseX={this.wordCard.mouseX}
        mouseY={this.wordCard.mouseY}  // ✅ Added this line
        isVisible={this.wordCard.isVisible}
        isSticky={this.wordCard.isSticky}
        onClose={this.handleCardClose.bind(this)}
        containerRect={containerRect}
      />
    )
  }

  private handleCardClose(): void {
    this.wordCard = {
      ...this.wordCard,
      isVisible: false,
      isSticky: false,
      word: ""
    }
    this.renderWordCard()
  }

  private startMonitoring(): void {
    if (!this.isEnabled || !this.isInitialized) return

    if (this.updateInterval) {
      clearInterval(this.updateInterval)
    }

    const captionContainer = document.querySelector(".captions-text")
    if (!captionContainer) {
      console.log("[YouTube Manipulator] No caption container found yet")
      setTimeout(() => this.startMonitoring(), 1000)
      return
    }

    this.addSubtitleHoverListeners()

    this.updateInterval = setInterval(() => {
      if (!window.location.href.includes("youtube.com/watch")) {
        if (this.updateInterval) {
          clearInterval(this.updateInterval)
          this.updateInterval = null
        }
        return
      }

      const currentText = this.getCaptionText()
      if (currentText && currentText !== this.lastCaptionText && this.isJapaneseText(currentText)) {
        this.lastCaptionText = currentText
        this.processCaptionSegments()
      }
    }, 500)
  }

  private addSubtitleHoverListeners(): void {
    const captionContainer = document.querySelector(".captions-text")
    if (!captionContainer) return

    const handleMouseEnter = () => {
      const video = document.querySelector("video") as HTMLVideoElement
      if (video && typeof video.pause === "function") {
        video.pause()
      }
    }

    const handleMouseLeave = () => {
      const video = document.querySelector("video") as HTMLVideoElement
      if (video && typeof video.play === "function") {
        video.play()
      }
    }

    captionContainer.addEventListener("mouseenter", handleMouseEnter)
    captionContainer.addEventListener("mouseleave", handleMouseLeave)
  }

  private getCaptionText(): string | null {
    const captionContainer = document.querySelector(".captions-text")
    if (!captionContainer) return null

    const segments = captionContainer.querySelectorAll(".ytp-caption-segment")
    if (segments.length === 0) return null

    return Array.from(segments)
      .map((segment) => segment.textContent?.trim())
      .filter((text) => text && text.length > 0)
      .join(" ")
  }

  private processCaptionSegments(): void {
    const segments = document.querySelectorAll(".ytp-caption-segment")

    segments.forEach((segment) => {
      const text = segment.textContent
      if (!text || !this.isJapaneseText(text)) return

      const tokens = this.tokenizeJapanese(text)
      if (tokens.length === 0) return

      const tempContainer = document.createElement("div")
      tempContainer.style.display = "contents"

      tempContainer.innerHTML = tokens
        .map(
          (token, index) =>
            `<span class="tokenized-word" data-word="${this.escapeHtml(token.surface_form)}" data-index="${index}">${this.escapeHtml(token.surface_form)}</span>`
        )
        .join("")

      tempContainer.querySelectorAll(".tokenized-word").forEach((wordElement) => {
        const word = wordElement.getAttribute("data-word")
        if (!word) return

        wordElement.addEventListener("mouseenter", (e) => {
          const rect = (e.target as HTMLElement).getBoundingClientRect()
          this.handleWordHover(word, rect.left + rect.width / 2, rect.top)
        })

        wordElement.addEventListener("mouseleave", () => {
          this.handleWordLeave()
        })

        wordElement.addEventListener("click", (e) => {
          e.stopPropagation()
          const rect = (e.target as HTMLElement).getBoundingClientRect()
          this.handleWordClick(word, rect.left + rect.width / 2, rect.top)
        })

        const htmlElement = wordElement as HTMLElement
        htmlElement.style.cursor = "pointer"
        htmlElement.style.padding = "2px 4px"
        htmlElement.style.borderRadius = "4px"
        htmlElement.style.transition = "background-color 0.2s"
        htmlElement.style.display = "inline"

        htmlElement.addEventListener("mouseenter", () => {
          htmlElement.style.backgroundColor = "rgba(255, 255, 255, 0.2)"
        })

        htmlElement.addEventListener("mouseleave", () => {
          htmlElement.style.backgroundColor = "transparent"
        })
      })

      segment.innerHTML = ""
      segment.appendChild(tempContainer)
    })
  }

  private escapeHtml(text: string): string {
    const div = document.createElement("div")
    div.textContent = text
    return div.innerHTML
  }

  private handleWordHover(word: string, mouseX: number, mouseY: number): void {
    this.wordCard = {
      word,
      mouseX,
      mouseY,
      isVisible: true,
      isSticky: false
    }
    this.renderWordCard()
  }

  private handleWordLeave(): void {
    if (!this.wordCard.isSticky) {
      this.wordCard.isVisible = false
      this.renderWordCard()
    }
  }

  private handleWordClick(word: string, mouseX: number, mouseY: number): void {
    this.wordCard = {
      word,
      mouseX,
      mouseY,
      isVisible: true,
      isSticky: true
    }
    this.renderWordCard()
  }

  private isJapaneseText(text: string): boolean {
    return /[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FAF]/.test(text)
  }

  private tokenizeJapanese(text: string): Token[] {
    if (!window.kuromojiTokenizer) return []
    return window.kuromojiTokenizer.tokenize(text)
  }

  private observeNavigation(): void {
    if (!this.isEnabled) return

    let currentUrl = window.location.href

    this.observer = new MutationObserver(() => {
      if (currentUrl !== window.location.href) {
        currentUrl = window.location.href
        this.lastCaptionText = ""
        this.wordCard = {
          word: "",
          mouseX: 0,
          mouseY: 0,
          isVisible: false,
          isSticky: false
        }
        this.renderWordCard()

        if (window.location.href.includes("youtube.com/watch")) {
          setTimeout(() => this.startMonitoring(), 1000)
        }
      }
    })

    this.observer.observe(document.body, {
      childList: true,
      subtree: true
    })
  }

  public setEnabled(enabled: boolean): void {
    const wasEnabled = this.isEnabled
    this.isEnabled = enabled

    console.log(`[YouTube Manipulator] ${enabled ? "Enabled" : "Disabled"}`)

    if (enabled && !wasEnabled) {
      this.init()
    } else if (!enabled && wasEnabled) {
      this.cleanup()
    }
  }

  private setupMessageListener(): void {
    if (typeof chrome !== "undefined" && chrome.runtime) {
      chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
        if (message.action === "setUseAutoGeneratedSubtitles") {
          this.setEnabled(message.useAutoGenerated)
          sendResponse({ success: true })
        }

        if (message.action === "getUseAutoGeneratedSubtitles") {
          sendResponse({ useAutoGenerated: this.isEnabled })
        }
      })
    }
  }

  private cleanup(): void {
    if (this.updateInterval) {
      clearInterval(this.updateInterval)
      this.updateInterval = null
    }

    if (this.observer) {
      this.observer.disconnect()
      this.observer = null
    }

    if (this.wordCardRoot) {
      this.wordCardRoot.unmount()
      this.wordCardRoot = null
    }

    if (this.wordCardContainer) {
      this.wordCardContainer.remove()
      this.wordCardContainer = null
    }

    this.lastCaptionText = ""
    this.wordCard = {
      word: "",
      mouseX: 0,
      mouseY: 0,
      isVisible: false,
      isSticky: false
    }
  }

  public destroy(): void {
    this.cleanup()
    this.isEnabled = false
    this.isInitialized = false
  }
}

let youtubeManipulator: YouTubeSubtitleManipulator | null = null

if (window.top === window.self) {
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initializeYouTubeManipulator)
  } else {
    initializeYouTubeManipulator()
  }
}

function initializeYouTubeManipulator() {
  if ((window as any).__bundaiYouTubeManipulatorInit) {
    return
  }
  (window as any).__bundaiYouTubeManipulatorInit = true

  if (youtubeManipulator) {
    youtubeManipulator.destroy()
  }

  youtubeManipulator = new YouTubeSubtitleManipulator()
  console.log("[YouTube Manipulator] YouTube subtitle manipulator initialized")
}

if (typeof chrome !== "undefined" && chrome.runtime) {
  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.action === "autoGeneratedToggled") {
      if (youtubeManipulator) {
        youtubeManipulator.setEnabled(message.useAutoGenerated)
      }
      sendResponse({ success: true })
    }
  })
}

let currentUrl = location.href
const urlObserver = new MutationObserver(() => {
  if (location.href !== currentUrl) {
    currentUrl = location.href
    console.log("[YouTube Manipulator] URL changed, reinitializing")

    setTimeout(() => {
      (window as any).__bundaiYouTubeManipulatorInit = false
      initializeYouTubeManipulator()
    }, 1000)
  }
})

urlObserver.observe(document.body, { childList: true, subtree: true })

window.addEventListener("beforeunload", () => {
  youtubeManipulator?.destroy()
  urlObserver.disconnect()
})

export { YouTubeSubtitleManipulator }